# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: GeekTOP - Новости из мира IT
name: GeekTOP
description: Новости из мира IT, технологий и т.д.
themecolor: '#202225'
imagehome: img/geektop.jpg
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'http://geektop.ru' # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jekyll


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

category_dir: blog
pagination: 
  enable: true
  per_page: 9
  title: ':title - Страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

exclude: ['node_modules', 'gulpfile.js', 'package.json', 'package.lock.json', 'js/common.js', 'npm-debug.log', 'css/main.sass', '**/Thumb.db', 'libs', 'sass', '**/*.DS_Store']

soc:
  <li><a href="#" class="fa fa-vk"></a></li>
  <li><a href="#" class="fa fa-facebook"></a></li>
  <li><a href="#" class="fa fa-odnoklassniki"></a></li>
  <li><a href="#" class="fa fa-instagram"></a></li>
  <li><a href="#" class="fa fa-rss"></a></li>

copyright: Копирование любой информации с данного сайта разрешено

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
